### ISSUE TITLE
Documenting something is way too hard

### ISSUE THREAD

**Issue by mhaberler** [machinekit/machinekit#100]
the current way of documenting is: 

- edit or create an asciidoc file under docs/src
- find somebody to add that to the git repo
- have next to no way how the visual appearance is (barring a build from git with --enable-build-documentation)

This makes it extremely unwieldy for a non-developer to contribute a fix, a fragment, or a  case study - in effect pushing all the work towards developers by turning off any drive-by contributors.

There should be a way to view, edit and add documentation online easily.

**Comment by luminize** [comment]
The PR #422 is ready for review.

**Comment by cdsteinkuehler** [comment]
On 1/9/2015 11:08 AM, Bas de Bruijn wrote:
> The PR #422 is ready for review.

It failed the ant and doc builds, but I'm guessing that's probably expected?

Should this be merged or held off until the buildbot catches up?

-- 
Charles Steinkuehler
charles@steinkuehler.net

**Comment by luminize** [comment]
yeah, building docs then there are none would be hard I guess.
John wants to sync with some of his work on the buildbot, and disabling the docs build was part of that

**Comment by zultron** [comment]
As usual I'm guilty of assuming everyone else knows what's in my brain.

PR #422 altogether removes the docs from the main Machinekit repo, which is why the docs builder fails, and thus the overall 'ant' builder.

Also guilty of making mountains of molehills.  I'll try removing the docs builder immediately & poking the build.  No real need to synch.

Tonight I'll do a quick scan of the PR for red flags, and if all looks good, I'll merge it.

**Comment by zultron** [comment]
Review of PR #422 is done.  There's a question and a minor problem I'd like addressed, and then this baby is ready to be merged.  REALLY nice work here, I can't say it enough.

**Comment by luminize** [comment]
I think this issue can be closed, please re-open if necessary

**Comment by zultron** [comment]
Agreed, slam-dunk!
