### ISSUE TITLE
Website: add google groups to search

### ISSUE THREAD

**Issue by machinekoder** [machinekit/machinekit#1340]
I think it would be nice if the search functionality on the Machinekit websites also includes the Machinekit Google Group because it contains lot's of valuable information not in the docs.

**Comment by ArcEye** [comment]
I can add it to the search params in the next couple of days.
May take a while to propagate it, that is down to Googles netbots.

**Comment by ArcEye** [comment]
The problem with this is that we can never own the site we want indexed, since Google does.

If I can get access to the header here https://groups.google.com/forum/#!forum/machinekit
I may be able to insert a meta-tag into it which will satisfy the verification process.
Have a feeling only @mhaberler has that, he probably set it up

![selection_006](https://user-images.githubusercontent.com/770392/34520072-0b01f7ca-f07f-11e7-8440-d89987d9a24c.jpg)

**Comment by ArcEye** [comment]
I have sent him and email, so see how we go

**Comment by machinekoder** [comment]
Okay good. Right now the search searches all google groups it seems.

**Comment by mhaberler** [comment]
@ArcEye @machinekoder  you are now owners of the google group

**Comment by ArcEye** [comment]
That does not work unfortunately.
The welcome message appears to be pretty much plain text and does not come within the index.html.
Even entering the meta-tag into the text does not result in verification.

All the other methods require ownership or access to the domain which we do not have.

As Google provides a search facility with the forum, I don't suppose they are much concerned about others specifically searching it from another engine.

If we can find a search syntax that only yields results from that forum, we could set up a link.
However `https://groups.google.com/forum/#!forum/machinekit: HAL` and similar do not bring up results exclusively from our forum.

Open to ideas.

**Comment by ArcEye** [comment]
Finally fixed it via a separate route.

Adding the specific forum to the google search proved impossible due to the ownership issues as above.
Adding the forum url into the search specs resulted in just the first bit of the url being parsed by google and results from all forums being displayed.

Hit upon a search url which resulted in specific results from our forum only.
`https://www.google.co.uk/search?&q=site%3Agroups.google.com%2Fd%2Fmsg%2Fmachinekit%2F%20`

The final char is a space and anything appended to it is searched

Got rid of the clunky branded search input box for the google cse and used a plain size limited input for google site search and another for Forum search.

After much buggering about to try to get alignment between disparate elements in the page, the result works 😄 

![selection_035](https://user-images.githubusercontent.com/770392/35091232-e5b62516-fc33-11e7-965a-7e6da5c0d0e7.png)

https://github.com/machinekit/machinekit-docs/pull/278 refers

**Comment by sirop** [comment]
Overlaps  in Opera 50.0 on Windows 8.1

![search_over](https://user-images.githubusercontent.com/1533811/35092440-afc7ac70-fc3f-11e7-9c9e-d1a2b53cea18.png)

**Comment by ArcEye** [comment]
That is not the page I created, it has not been rendered yet.

Look at http://preview.machinekit.io

**Comment by sirop** [comment]
The it looks like 

![search_over1](https://user-images.githubusercontent.com/1533811/35093170-ed45ef38-fc41-11e7-8111-bd95b92e554c.png)

in Opera 50.0 .

**Comment by ArcEye** [comment]
Opera seems to have decided there is room for the first box and Firefox thinks it only fits on the next line
I'll experiment with pushing it down

**Comment by ArcEye** [comment]
OK, adding a link to the Forum in the top line, pushes the search boxes down in Opera

![selection_036](https://user-images.githubusercontent.com/770392/35093949-bceedb2a-fc3b-11e7-9f16-b1f085596570.png)

and also displays OK still in Firefox

![selection_037](https://user-images.githubusercontent.com/770392/35094002-e74bc77a-fc3b-11e7-8dd0-d97ccea3c054.png)

I'll push another PR and test

**Comment by ArcEye** [comment]
https://github.com/machinekit/machinekit-docs/pull/279

**Comment by ArcEye** [comment]
Now built and tested.
I reverted to the overlay results method, because it worked best in both browser types.

If checking, make sure you clear your cache and force refresh the browser (Ctrl F5 in Firefox), 
or you may get peculiar results since not only the webpage code but the google cse settings have changed.

Interestingly there is a distinct difference to the results pages from Firefox with adblocker enabled

![selection_038](https://user-images.githubusercontent.com/770392/35109848-5b031d98-fc6f-11e7-972d-b64f41b455fd.png)

and Opera without.

![selection_039](https://user-images.githubusercontent.com/770392/35109874-6dd596f8-fc6f-11e7-82ed-f9057f3029ac.png)

If you entered `comp` instead of `instcomp`, you would get half a page of 'ambulance chasing' law firms adverts prior to the actual results in Opera.

Even disabling adblocker, does not produce adverts in Firefox

Pretty much says it all about google's sole motivation and why I don't touch Chrome or anything derived from it.

**Comment by ArcEye** [comment]
Resolved as far as can be
