### ISSUE TITLE
HAL API Changes

### ISSUE THREAD

**Issue by cdsteinkuehler** [machinekit/machinekit#237]
This is a "meta" issue to discuss desired changes to HAL that will break or change the API and thus require updates to many pieces (HAL language bindings, existing components, etc).  There are a few of these already:
- [x] Add support for Machinetalk (remote HAL components, HAL groups, ring buffers, etc)
- [x] Separate component module loading and instance creation, so it is possible to dynamically add more components of an already loaded type (currently, the number of instances must be known at module load time, which seems quite restrictive given the new distributed, dynamic nature of HAL with Machinetalk)
- [ ] Support accessor functions for HAL data types to enhance portability and avoid real-time problems when migrating to multi-core and non-x86 platforms
- [ ] Get rid of the rate-monotonic approach to exclusive access - the multicore's are already there. [from @mhaberler below; edit by @zultron]

The intent is to try and update HAL and the required bindings/API once with a "breaks everything" merge and hopefully not have to break things again going forward.

**Comment by mhaberler** [comment]
I did some reorganisation of the hal library, see #502 - more amenable to the casual reader instead of this 120kB blob

once that's in I'll finish support for instantiable comps; it will be less than perfect but hopefully workable

**Comment by mhaberler** [comment]
One feature I consider putting on a deprecation path is the 'param/pin alias' feature

It adds considerable complexity, and seems to be unused - there is a single mention TCL file which demonstrates some two-pass loading feature, so I think it's safe to #define out and see what is coming up, likely nothing

**Comment by mhaberler** [comment]
separate loading and instantiation: making good progress here

I added a feature "userfunct" - you can trigger a call to a user-defined function in a component from say halcmd or Python

example comp: see userfunct_demo in http://git.mah.priv.at/gitweb?p=emc2-dev.git;a=blob;f=src/hal/userfunct-example/ufdemo.c;h=1322782c32590ae250d3de7160fa960b486c5d03;hb=ce7066a119cd6ec9961a8f992d1f01e72c72b2ee

I'm going to layer component instance creation/exit on top of that
so loading will do either nothing or just one instance

halcmd call comp.manage newinst foo bar baz, # peng, new instance (this will be wrapped into something easier comprehensible)
halcmd call comp.manage delinst foo  #instance foo exits 

this needs an extended hal_init() which takes the funct parameter, and some library support to make it easier but the bits are in place

**Comment by mhaberler** [comment]
instantiation is fully addressed in the HAL instantiation branch

**Comment by mhaberler** [comment]
see also https://github.com/machinekit/machinekit/issues/239#issuecomment-124058210

**Comment by mhaberler** [comment]
here is an idea I've been toying around for a while, it might make HAL use simpler while making better use of multicores, which are heading our way no matter what

problem: if you have a job which requires HAL but does not need an RT thread, you need a usercomp.

downside of a usercomp: you need to write it, even if the job could mostly or completely be achieved by combining existing RT comps. There is no good way to reuse RT comps for non-RT work except for interacting through pins or ringbuffers.

upside of a usercomp: you have the full Linux API, and any libraries at hand. Files, sockets, poll, what have you.

idea: assume we had a feature like this:
````
  newthread vanilla  1000000 posix cpu=2
````
now we can addf any funct of _any RT comp_ onto the vanilla (non-RT Linux-style) thread, and the execution time of this thread would NOT account against the RT cycle budget. We might even waste a core just for a specific purpose.

that is (implicitly) already possible in the 'posix' flavor, but then we have no RT option there. For RT-preempt that feature is trivial to implement. For RTAI it is almost impossible. But I do not think feature parity for all flavors is an absolute must.

It seems it is possible with Xenomai 2 as well, Xenomai 3 for sure; have a look at this thread: https://xenomai.org/pipermail/xenomai/2015-July/034745.html


there is a downside of this approach: reduced separation. People load more of their 'usercomps' into RT, more chance to bring down RT in one go, whereas in the one-process-per-usercomp scenario that is not the case. But it is not an issue if just reusing existing RT comps because those would succeed/fail just alike in RT or vanilla.


it is not required for what we're doing right now with making HAL SMP-safe, but it would open options

**Comment by ArcEye** [comment]
I tend to write userspace components over rt ones, except where a timing issue requires rt.
As you say it allows full use of system libraries, ports etc. in my case allows Qt GUIs and generally to program in C++ whilst accessing HAL and NML internals.

Some components have no need to be rt at all, unless used as part of something time critical.
Using some of the logic components for instance (and or not etc) to manipulate an output, would be just as useful in a userspace setting.

Whether there would be any widespread takeup and use of the ability, I am less sure.

**Comment by mhaberler** [comment]
anyway I gave it a try, not much work: https://github.com/machinekit/machinekit/pull/732

it was a welcome opportunity to make the thread API a bit more flexible which will be needed for hal-triggers, which are closely related functionally

it's also a good standalone example for an extension which goes from a new rtapi command option through halcmd, cython, protobuf, rtapi_app, HAL, RTAPI and down to the flavor layer

**Comment by ArcEye** [comment]
Think this is historical now, multicore is merged, the API is considerably changed
