### ISSUE TITLE
Separate HAL Module Loading and Instance Creation

### ISSUE THREAD

**Issue by cdsteinkuehler** [machinekit/machinekit#240]
Currently the number of desired instances of a HAL modules must be known at module load time and cannot be changed once a module is loaded.  This is very limiting in the new distributed HAL and Machinetalk context, where a specific HAL instance is not necessarily directly tied to a specific "machine" with all details of the machine known at startup.

Much of the code for this already exists, but was apparently never enabled.

The HAL API should also be updated to make it easy to dynamically add an instance of a specific HAL component regardless of whether or not the module is already loaded or has any other instances.

**Comment by cdsteinkuehler** [comment]
Would it be possible to call the rtapi_app_main() init function more than once for some components, using a different component name?  A limited version of being able to dynamically create instances would be helpful for modular configuration files.  For example a system that might need to load 3 PID controllers for positioning, and another 2 for temperature control wouldn't have to know .  If this could be done easily for fairly generic HAL modules (ie: things like PID, limit, and mux that just talk to HAL and not directly to hardware) it would be handy when generating flexible configuration files.

**Comment by mhaberler** [comment]
interesting idea; still thinking through it - hence remarks likely incomplete:
- most comps as written take their name either from the compiled-in module name or from the 'names=' parameter - those with a hard-compiled in name would be excluded (mostly old comps written in C) unless rewritten
- unsure this will for kthread styles due to compile-time symbol resolution (likely yes though)
- rtapi_app_main(void) does not take params per se, those come from the command line, which is fairly kernel-specific for kthreads but I could imagine cooking up a special argument list for such an instantiation for userland threads
- that - say 'halcmd instantiate <existing modname> names=.... args..' call would have to refer to an existing module name so the 'parent' comp can be found, meaning either there's already a loaded 'modname'. IOW: the instantiate command would have to refer to a/the name of the previous instantiation, whatever that was, so it could be located; meaning there are still name dependencies (there is no such thing as a comp "type name" like "type or2" which could be referred to)

let me read through some comp output, could be worth a try !

**Comment by strahlex** [comment]
Just to note: Yesterday I ran into a maximum 16 names error (I had a list with 21 names). I don't know where this number comes from, but it may be necessary to increase that number too to support bigger modular HAL configurations.

**Comment by cdsteinkuehler** [comment]
I'm thinking something _really_ brain-dead might possibly work.  To use
the pid component as an example, what I'd like to be able to do is
something like:

loadrt pid names=joint0,joint1,joint2,joint3

....

loadrt pid names=therm0, therm1

It seems like this is mostly handled by loading the module once (on
first reference) and calling the init function more than once (assuming
no static data allocated on load...all statics would need to be
allocated in the init function).

What am I missing that makes this super hard for the limited case of pid
(and perhaps other "well behaved" components)?

-- 
Charles Steinkuehler
charles@steinkuehler.net

**Comment by mhaberler** [comment]
I tried with the 'let's code this until we hit the brick wall' method. This is the brick wall:

module arguments are passed at module load time, and are frozen thereafter

frozen for good if this is kthreads (I dont see a way to modify the argument list of an already inserted kernel module)

in the case of userland threads, this method is emulated by allocating params, patching their address into the symbol table of the module just loaded, and then calling rtapi_app_main(void)

now, if you were to overwrite those params before calling rtapi_app_main() again, the module params of the first loaded 'instance' get overwritten, and they would be shared (not per-instance)

sorry, I do not see a way to do this even in simple cases without wholesale damage, short of a redesign of the HAL API which separates comp and instance, and hence breaks every single call of hal_pin_new() ff as the comp_id parameter would now have to refer to an instance, not a comp

**Comment by mhaberler** [comment]
@strahlex - compile in limits in stone age comps:

mah@nwheezy:~/machinekit-prepare/src$ grep -r 'define.*MAX_CHAN' hal

hal/drivers/hal_tiro.c:#define MAX_CHAN 4
hal/drivers/hal_pru_generic/hal_pru_generic.c:#define MAX_CHAN 8
hal/drivers/hal_stg.c:#define MAX_CHAN 8
hal/drivers/hal_vti.h:#define MAX_CHANS  4
hal/drivers/hal_stg.h:#define MAX_CHANS  8
hal/drivers/hal_vti.c:#define MAX_CHAN 8
hal/drivers/pcl720.comp:#define MAX_CHAN 8
hal/components/supply.c:#define MAX_CHAN 16
hal/components/mux_generic.c:#define MAX_CHAN 100
hal/components/bldc.comp:#define MAX_CHAN 8
hal/components/at_pid.c:#define MAX_CHAN            16
hal/components/pid.c:#define MAX_CHAN 16
hal/components/encoder.c:#define MAX_CHAN 8
hal/components/matrix_kb.c:#define MAX_CHAN 8
hal/components/encoder_ratio.c:#define MAX_CHAN 8
hal/components/sim_encoder.c:#define MAX_CHAN 8
hal/components/siggen.c:#define MAX_CHAN 16
hal/components/lcd.c:#define MAX_CHAN 16
hal/components/pwmgen.c:#define MAX_CHAN 8
hal/components/counter.c:#define MAX_CHAN 8
hal/components/stepgen.c:#define MAX_CHAN 16

**Comment by strahlex** [comment]
And what if we make a wrapper function around loadrt that accumulates all uses of loadrt and does a single loadrt at the end? This of course would not work for the interactive mode, but for the use of splitting a HAL configurations in a modular fashion. Every HAL configuration part would need a setup "function" and a body function. When loading the whole HAL configuration first all setup functions containing the HAL component instantiation are called. These are accumulated and loadrt is called single time for each component. After the setup the body functions are called like a normal HAL file.

**Comment by cdsteinkuehler** [comment]
On 1/6/2015 4:17 AM, Michael Haberler wrote:
> I tried with the 'let's code this until we hit the brick wall' method. This is the brick wall:
> 
> module arguments are passed at module load time, and are frozen thereafter

I wasn't thinking you would pass arguments on module load, instead you
just load the module code into memory on first reference and call
rtapi_app_main() with a custom string to create a new instance.

This could be handled without changing the module code in user-land, but
we'd probably need a new api for kernel modules.  Could it be as simple as:

int rtapi_app_main()
{
    ...code...
}

Turns into:

int rtapi_app_main()
{
    // Nothing to see here...
}

int rtapi_new_inst()
{
    ...code...
}

-- 
Charles Steinkuehler
charles@steinkuehler.net

**Comment by mhaberler** [comment]
before going into the next idea - do you concur that splitting the problem like so would help already:

- a ton of legacy comps which are not cloneable
- a few cloneable ones (which would have to be rewritten)?

it seems to me the 'must be clonable'  requirement goes mostly towards mundane comps like or2 etc?

**Comment by cdsteinkuehler** [comment]
On 1/6/2015 3:50 PM, Michael Haberler wrote:
> before going into the next idea - do you concur that splitting the problem like so would help already:
> 
> - a ton of legacy comps which are not cloneable
> - a few cloneable ones (which would have to be rewritten)?
> 
> it seems to me the 'must be clonable'  requirement goes mostly towards mundane comps like or2 etc?

I agree that there are lots of existing HAL components that it makes no
sense to load more than once.  Pretty much anything talking to hardware,
whether it's a parallel port, PRU, or Mesa card.

I think the only viable candidates are really the HAL only components
(only HAL I/O pins, no "outside world" interaction), and I'm completely
OK with not all of these being converted at once if it makes coding easier.

The specific components I'd like to be able to instantiate independently
are things like PID, limit, and other "glue" logic (or2, etc) that would
go in-between the "primary" components like motion on one side and the
hardware drivers on the other.

My goal is to be able to build HAL file 'snippets' that would be things
like a PID controlled stepper axis, a heater control, or a fan driver,
then a top-level HAL file would be built mostly by including these
smaller modules.  This is a *LOT* easier if you don't have to know ahead
of time how many PID controls or AND gates are required.

-- 
Charles Steinkuehler
charles@steinkuehler.net

**Comment by mhaberler** [comment]
a consequence of the instance/comp distinction would be that hal_exit() would just end the current instance, not all of them

but the more I think of it, this class/instance separation does away with the need for multiple instantiations   in a single command line, one could just write

loadrt or2
newinst or2 foo
newinst or2 bar

instead of 
newinst or2 names=foo, bar

and on unload

delinst foo
delinst bar

the latter names=<list of instance names> convention was just needed because of the lack of separation of loading and instantiation, and since that is now in place the names= scheme isnt needed anymore - comps need to get the instantiation of _one_ instance right, done

(also the loadrt or2 could be done away - loading could happen automatically on first reference)

**Comment by mhaberler** [comment]
researching how the kernel module parameter handling works - the parsing and and dissection of arguments according to the param descriptor linker section magic is all done in-kernel:

http://www.tsri.com/jeneral/kernel/kernel/module.c/pm/PM-INIT_MODULE.html

with a bit of luck parse_args() could be recycled to work on say the argument of a procfs write to pass the equivalent of a module argument vector

**Comment by mhaberler** [comment]
well it seems with a minor restriction on parameter use this could work:  parameters are valid only during a 'newinst' call; a module using the parameters beyond our new rtapi_new_inst() call need to save those values in the instance data blob

**Comment by mhaberler** [comment]
I guess I found a simpler way to smuggle per-instance parameters into kthreads modules (It's trivial for userland threads anyway):

- export module parameters r/w in sysfs (see http://lwn.net/Articles/85443/ - need nonzero permissions)
- load the module
- instantiating the module:
- 1: set the desired params by writing to /sys/modules/<comptype>/parameters/<paramname>
- 2: call the newinst method via sysfs or procfs - this will cause rtapi_new_inst() to be called
- 3: first thing rtapi_new_inst() does is allocate the per-instance data struct via hal_malloc(), and copy the current param values to it

for legacy modules, "instantiation" is as-is
for instantiable modules, the rtapi_app_main being a dummy, load-time params will be ignored (which is ok)

what remains to be solved is a load-time method to distinguish legacy and instantiable modules; probably some linker-section trick does it - or we'll have a per-module 'newinst' sysfs entry for instantiable ones; if this entry is present, need to treat the module as instantiable

what we get for free is the whole parse_args/parameter setting infrastructure in the kernel, no coding required

this is all that is needed to enable module params in sysfs:

https://github.com/mhaberler/machinekit/commit/4c8530c922130110709295507e74f077295a90d8

**Comment by cdsteinkuehler** [comment]
On 1/7/2015 6:42 AM, Michael Haberler wrote:
> what remains to be solved is a load-time method to distinguish legacy
> and instantiable modules; probably some linker-section trick does it
> - or we'll have a per-module 'newinst' sysfs entry for instantiable
> ones; if this entry is present, need to treat the module as
> instantiable

Can't the rtapi_app_main() function do something to tell rtapi that it's
capable of instantiating more than one module (like
rtapi_register_multi_capable() or some-such)?  Legacy components
wouldn't do this, so rtapi would know they couldn't be called again.

Or you could leverage the existing module defines and export a specific
name/value for new style components:

static int multi_inst = 1;
RTAPI_MP_INT(multi_inst, "Supports multiple instances");

If it's easy to check for the existence of the newinst() entry point,
that could work too.

-- 
Charles Steinkuehler
charles@steinkuehler.net

**Comment by mhaberler** [comment]
close - entry points can be detected, which will help backwards compatibility

we'll need a few new macros anyway, so far I have:

RTAPI_API_VERSION(2);  // marks it as instantiable
RTAPI_COMP_TYPE("test", "component type name, used as instance template");

the newinst call will then roughly look like 'newinst("test","testinstancename", "arguments")

**Comment by mhaberler** [comment]
thinking through the impact and what's needed:

- hal_comp_t will be repurposed to act as component _instance_ descriptor
- there needs to be a new HAL object, the component type descriptor, which is referred to be the instance descriptors by means of a type id or a pointer; lets call it the hal_comptype_t struct for now

legacy API support/unchanged comps:
- hal_init() will - besides the hal_comp_t object - implicitly also create a hal_comptype_t object and refer to it
- the hal_comptype_t is marked as non-instantiable, implying legacy behavior

revised API for instantiable components:
- a new variant of the hal_init() call which takes a type name (e.g. "or2") as well as pointers to the new_inst and del_inst functions, which will must be present in the new comp
- this hal_init() call will NOT create an instance, just the type object

usage flow of loading/unloading and instantiation - legacy:
- loadrt compname ..parameters.. : implicit instantiation through count=/names=, fixed number of instances
- unloadrt compname .. unchanged

usage flow of loading and instantiation - comps with new API (determined by inspecting the comp, eg for certain symbols or linker sections):
- loadrt compname  : this will only load the shared object and create the type object, but no instances
- collect params; in case of kthreads write to /sys/modules/..compname../parameters/..paramname.. sysfs files; with userland threads no need since directly callable RT functions from rtapi_app, so any param passing possible - just need to make sure the component-side API doesnt expose the difference
- call the new_inst method - which actually creates instances
- del_inst ..name.. deletes instance by going through the del_inst method, type object+shared object remain loaded
- unloadrt compname : deletes all instances by going through the instance list and matching the type id, deletes the type object, then unloads the shared object/module

remote comps: a neat idea I still need to think through more would be remote comp instances which spring into existance by reference from a UI - even if the only have a single HAL pin

groups: unaffected

remote UI's - affected as far as the remote comp API changes; likely minor

comp.py: needs to be transmogrifed to support the new API; maybe with a flag to do so

note to self: add more impact here as it surfaces

**Comment by mhaberler** [comment]
working example - actually useful:  https://gist.github.com/mhaberler/8fa89bbc12ac93b2de15

**Comment by mhaberler** [comment]
done and merged, in the instantiation branch.
