### ISSUE TITLE
`flavor` logic contains surprises

### ISSUE THREAD

**Issue by zultron** [machinekit/machinekit#263]
@ArcEye discovered, when running MK under an RTAI kernel but not realizing RTAI modules were missing, that MK was instead running `posix` threads.  The problem is that MK appeared to be happily working, but Mick didn't know RTAI threads weren't running until he accidentally discovered it.

Of course this is not only surprising to users (if they discover it at all), but also potentially dangerous.

I propose this be addressed in this way to ensure that at least, if the user knows what kernel is running, there will be no surprises:

- If the `FLAVOR` environment variable is set, insist on those threads, and bomb out if those threads aren't available.
  - This may be the current behavior; I haven't checked.
- If no `FLAVOR` environment variable is set, then if `flavor` detects some particular hard-RT capabilities in the running kernel, then insist on running an applicable hard-RT thread flavor.
  - If no thread modules exist for that kernel, bomb out with a message saying why, and noting that the `FLAVOR` variable can be used to force different thread modules.
  - The Xenomai kernel has two thread flavors; in this case, either one is valid, with `xenomai` (userland) preferred.

**Update:** @kinsamanka fixed the following in #268.
~~Related problem:  When both `xenomai-kernel` and `xenomai` (userland) modules exist, `xenomai-kernel` is the preferred flavor, despite being deprecated.  (This is probably an issue I introduced myself.)~~

**Comment by zultron** [comment]
Closing (wontfix):  no recent problem reports

**Comment by ArcEye** [comment]
NB.  (pre-existing related problem - no fix required)
I hit another rtai problem just recently when testing @mhaberler branch with a rtai build.

I was building against the 3.8.1-rtai kernel, but because I had the kernel sources for 3.8.17 on that machine, at some point in the build, configure had selected those sources instead of the 3.8.1 kernel headers.

It is just not going to occur for most people and is solved simply by having several /usr/src directories, one per kernel and a symlink which points to the right one for that kernel.

That is the strategy I used sucessfully previously, when test rtai builds.

Just for info, if a wholesale change to kernel determination is ever considered.

**Comment by zultron** [comment]
@ArcEye, yeah, you can control which RTAI kernel sources with `./configure --with-rtai-kernel-sources=/usr/src/version`.  The Xenomai kthreads automatically detect multiple sets of kernel sources (in standard locations) and build modules for each set.  I originally couldn't get that to work with upstream RTAI, something about there only being one `rtai-config` script.  To address this problem, I later contributed some changes to ShabbyX's repo that enable RTAI to support multiple kernels on a single machine, and there's surely some other workaround.  Anyway, I've lost interest, but that shouldn't stop another with a wild hare inserted into an unlikely part of his anatomy.
