### ISSUE TITLE
Build system is falling apart

### ISSUE THREAD

**Issue by zultron** [machinekit/machinekit#336]
The build system is becoming more and more unmaintainable.

Of course the old problems persist:
- So complicated and contrived that whenever someone modifies it, new problems are introduced
- The distinction between 'RIP' and non-'RIP'/system installs is the source of many problems
  - Changes that work with RIP build break in system build
  - Setting `${prefix}` inside of `configure.in` doesn't work as expected, leading to horribleness like `scripts/gen-rtapi.ini.sh.in.tmpl` which must be processed _three times_ before rendering a correct `rtapi.ini` file
  - Shared object files and `rpath` links repeatedly break
- General inflexibility causes headaches whenever something new is introduced; it took almost a week for the first version of the UB hack that builds separate sets of modules for each thread flavor, much more time since, and that still has unresolved issues.

New observed problems:
- Cython build issues
  - Non-RIP install:  Cython shared object files like `rtapi.so` are correctly installed into the python path, but also into `/usr/lib`; `rtapi_app_*` can try (and fail) to load this instead of the RT module `rtapi.so` in some circumstances
  - The new Cython `hal/cython/Submakefile` is a horrible thing whose utter nastiness can't be blamed upon its author, but rather is a testament to how difficult it must have been to integrate the generation of Cython C sources and then build of those sources into the build system.
- Installing header files into a subdirectory, such as `../include/userpci`, is an exception to the usual pattern of putting everything into `../include`, and took two tries to get working, and still with no general solution.

...and the list goes on.

The solution is to replace the build system.  Here are the things I see need to be done:
- Split off any pieces that we plan to split off to make this easier
  - Documentation, as noted in #100 
  - Splitting out GUIs and other non-core parts; I'm unaware of current related issues in the tracker
- Figure out what the new build system should look like
  - I have written a cmake configuration that builds much of the core already, and am partial to this
  - Another obvious alternative is `automake`, a natural complement to the existing `autoconf` config
- Implement it
  - It is likely possible to develop the new build system alongside the existing system for minimal disruption; I've seen this done with at least cmake (FreeCAD project)
  - Fix packaging for new build system

**Comment by zultron** [comment]
Another example of how broken the build system is in #443.  These antics would be completely unnecessary if the 'RIP' build distinction didn't exist, and `$prefix` were not defined in `configure.in`.

**Comment by strahlex** [comment]
`$prefix` is not the only variable. At some point someone has to rework the whole build system. 

Just an idea, if we do not have the expertise to rework the build system using cmake or anything else maybe we could crowdfund it and hire someone capable of doing this. Maybe https://www.bountysource.com/?

**Comment by kinsamanka** [comment]
Does it mean we can remove RIP installs?  :-)

**Comment by zultron** [comment]
It doesn't seem there's any lack of expertise on the build system.  @kinsamanka has already split out the UIs, I already have an old branch that builds a lot of the core stuff with cmake, and @luminize (the latest to tear out hair while modifying it) has already split off the docs.  For me it's just a matter of time and priorities to start putting those pieces together and see what's left.

This is still on my list, though, and ties into the 'master daemon' project's goal of getting complete unit tests into package builds, [building packages in OBS][1] (almost working), and creating a duplicable Buildbot system so that the project doesn't depend so much on this one critical piece of infrastructure.

And YES, may the RIP install Rest In Peace!

[1]:  https://build.opensuse.org/project/show/home:zultron:machinekit

**Comment by bobvanderlinden** [comment]
@zultron Where can I find your progress on cmake for the core libraries? Is it still up-to-date?
I found https://github.com/zultron/machinekit/tree/cmake and https://github.com/kinsamanka/machinekit-libnml, but they seemed somewhat out-of-date.

I've been experimenting with building machinekit with cmake as well.
You can see the results here: https://github.com/bobvanderlinden/machinekit/tree/cmake/projects

I wanted this to be somewhat easy to keep up-to-date, so I've started working on cmake in a fork of the machinekit repository. Hopefully git does a good enough job of keeping track of the changes and merges should be possible this way.

The 'subprojects' are structured as `${project}/{include,src}` with a `CMakeLists.txt` next to the include and src directories. This means that I've moved the source and header files for the moment from `${machinekit}/src/`.

All projects are included in a global `CMakeLists.txt`, where (for the moment) external libraries are configured, global defines added and config.h created. a bit like the original configure.ac does. Because all projects are included in the global cmake file, subprojects can link to eachother as well as expose their include-directories. CMake automatically keeps track of the dependencies and the order in which the projects(/libraries/executables) need to be build.

At the moment I only touched the core of machinekit. No docs, no guis. I just want the bare minimum to run on my desktop/laptop. That means only the simulator. I don't know exactly how Xenomai and the other real-time systems work, so for the moment those options are not there yet.

Lastly, I couldn't find a nice way to let autoconf and cmake cooperate, so I'm trying to get cmake to do everything. I'm not certain whether this is a good idea or not, but it does result in a cleaner environment to make progress (while keeping sanity). This does also mean a lot of configuration-options are gone.

It is rather incomplete at the moment, but I wanted to know whether this is indeed a direction we want to go for the core of machinekit?

**Comment by luminize** [comment]
Hi Bob, Welcome! (to others, I know Bob)
Work will be much appreciated on this i'm sure!

**Comment by mhaberler** [comment]
@bobvanderlinden - welcome and great you are taking a stab at this long-standing issue! it is sorely needed and definitely still a huge problem.

There have  been issues filed related to that - in particular about splitting up the machinekit package into several independent ones; in particular the (g)UI's could be farmed out, but for a start, disabling them is fine

I'm happy to coach as needed - you can find me on skype mhaberler and https://gitter.im/mhaberler !

**Comment by bobvanderlinden** [comment]
Hi @luminize !
@mhaberler Yes, @luminize told me about gitter. I've added you.

**Comment by zultron** [comment]
Hi @bobvanderlinden,

You found my latest cmake branches from before Machinekit existed, pretty old!

I was waiting for the spinning off of UIs into their own git repos before thinking about starting a new build system from scratch again.  Maybe that's not necessary, and it's great someone else is taking initiative.

I had one unresolved question about cmake.  Kernel threads (esp. RTAI) depend on Linux's wacky 'kbuild' system.  The current build system builds modules for both userland and kernel threads with the same set of rules.  Accomplishing that is certainly one (of many) source(s) of ugliness in the `make` rules, but at least it provides the benefit of only having to define a module & its sources once, and the module is then built for all flavors.  I didn't get far enough with cmake to find out whether it could generate the kbuild config.  As far as I know, it could be trivial, impossible, or anything in between!

**Comment by bobvanderlinden** [comment]
@zultron As an experiment I had already build shmdrv using kbuild in cmake: https://github.com/bobvanderlinden/machinekit/blob/cmake/projects/rtapi/shmdrv/CMakeLists.txt
I'm not sure yet how well this translates to other modules.

Another 'edge' case is building the .proto files, which is done here: https://github.com/bobvanderlinden/machinekit/blob/cmake/projects/machinetalk/mtalk_proto/CMakeLists.txt

However I initially thought to work on this to more easily run Machinekit's simulator on my desktop/laptop (which runs ArchLinux and NixOS). I used the python API of LinuxCNC, but after the conversation with @mhaberler yesterday on Skype it seems better to focus attention to getting a client-api for haltalk+mkwrapper using protobufs. First a initial setup for Python to get a better feel for things and after that (my goal) an API for nodejs.

I still believe it would be better if the simulator could be run on other distros as well, but from what I understood it's not worth the effort. Or at least not as useful as the haltalk+mkwrapper client APIs.

**Comment by zultron** [comment]
Hi @bobvanderlinden, I've forgotten all my cmake, but your tests look promising.  I suppose cmake macros could be used to generalize RTAPI module builds, hiding userspace/kthread build differences and simplifying module and source definitions.

Any idea how out-of-tree comps might work?

One more corner case is Cython, maybe already addressed by others, according to Google.

**Comment by bobvanderlinden** [comment]
If you could generalize the RTAPI builds and place those abstractions in a cmake file, you could expose the cmake file in `/usr/share/cmake-*/Modules/` or `/usr/share/machinekit/CMakeModules`. That way the build generalizations can be reused in the out-of-tree comps.
I haven't seen any projects exposing their cmake modules when it installs, but it might be a viable way to do so.

I have no experience with Cython. I'm guessing you found this project as well? https://github.com/thewtex/cython-cmake-example

**Comment by zultron** [comment]
@bobvanderlinden, I'm looking at your `cmake` branch.  I'm able to build it with no problem.  Nice!

Why are many files moved from the `src/` directory into `projects/`?  Is that a cmake thing?

**Comment by bobvanderlinden** [comment]
@zultron I wanted to split `include` and `src` directories for each 'subproject', that's why I introduced the `projects/` directory. That way each subproject would have a `src/` and an `include/`. Each subproject would be built into a binary (`.a`, `.so` or `.o`) independently. It makes sure you're not `#include <...>`-ing files that your subproject is not depending on. CMake makes sure the right include-directories are used (only those include directories that your subproject is depending on). It also helped a bit to know which projects were depending on which other ones due to missing include files in the compile errors while working on this.

At the time I was mostly doing this to get a feel for Machinekit/LinuxCNC's structure, as it is quite big.

**Comment by zultron** [comment]
@bobvanderlinden, ah, thanks for the explanation.  I'm re-learning the cmake I once knew, which was very little to begin with!

So, is the `#include` issue related to avoiding the need for e.g. `target_include_directories()`?

I'm just trying to get `hal`, `rtapi` and `machinetalk` compiling for now.  You made a great start!  I'm getting close to having Cython working, following https://github.com/thewtex/cython-cmake-example.

**Comment by bobvanderlinden** [comment]
No, you need to do `target_include_directories`, but it forces you to specify all depending projects in `target_include_directories`, otherwise the compiler will tell you it couldn't find the `#include` file.

For instance for: https://github.com/bobvanderlinden/machinekit/blob/cmake/projects/emc/nml_intf/CMakeLists.txt
It would previously allow you to include files from posemath, nml, etc without explicitly specifying the `linuxcnc` subproject is depending on those other projects. It would cause errors at link-time if a dependency was missed, now it'll cause errors at compile time.

**Comment by zultron** [comment]
Yes, I'm continuing from your branch, which is really spiffy.  There are still a bunch of chores left, but Cython is out of the way, and your ProtoBuf build works great.  I predict the `comp` modules will require overcoming the CMake module-writing learning curve.

My goal is to get the `nosetests` working only.  :)

**Comment by zultron** [comment]
I have a [PR][1] against @bobvanderlinden's repo that adds CMake configs for the Cython bindings and comps (not instcomps).  Combined with his work, it seems like it's starting to look like a skeleton.

It looks really slick.  As an example, [these lines][2] were squashed down to [these][3].  The overall logic of the configuration is so much clearer; [these functions][4] (ignore the last!) are almost readable, whereas their counterparts are spread around `hal/components/Submakefile` and `hal/components/mkconv.sh` with difficult logic.

There's still a lot of work to go, but this seems like a really good thing.  We'll get to throw away the RIP build, and it looks like Machinekit can run directly out of the build tree, and no recompile needed before running `make install`.  That means no need to compile twice for the CI system, since the regression tests can run in the tree during the package build (though it would still be best to package the tests as well).  And because the system is understandable by mere mortals, it will be easy to add new parts without breaking old parts, and these mysterious dependency problems can be cleared up.  Other annoyances may be solved too, such as we can stop linking libs to rtapi_app instead of linking them to the modules they belong with because the plumbing will suddenly become easy; this will clear the way to build on systems with newer linkers.

[1]: https://github.com/bobvanderlinden/machinekit/pull/1
[2]: https://github.com/zultron/machinekit/blob/cmake-bob/projects/hal/components/Submakefile#L129-L167
[3]: https://github.com/zultron/machinekit/blob/cmake-bob/projects/hal/components/CMakeLists.txt#L15-L25
[4]: https://github.com/zultron/machinekit/blob/cmake-bob/projects/cmake/UseHALComp.cmake

**Comment by RunningLight** [comment]
To quote the high school kids I've been working with, this is frickin'
awesome.

**Comment by bobvanderlinden** [comment]
That's a great use of `.cmake` files! The python stuff is somewhat 

The comp.py isn't build yet though for me. Try `git clean -xdf` and `mkdir build && (cd build && cmake ..) && cmake -C build`. I think it's working for you because you already have comp.py in `hal/utils/`.
I think as a general rule, no files should be generated in `*_SOURCE_DIR` and only in `CMAKE_CURRENT_BINARY_DIR` (which is inside `build/`). That way no extra gitignore rules are needed as the git repository stays clean.

Also, instead of using `${MACHINEKIT_SOURCE_DIR}/rtapi/rtapi/include` you could use `$<TARGET_PROPERTY:rtapi,INTERFACE_INCLUDE_DIRECTORIES>`. That way we could more easily move things around when needed. Not sure whether that works nicely from a `.cmake` file though.

I'll give both changes a try. We'll see how that goes :P.

**Comment by zultron** [comment]
@bobvanderlinden,

I fixed the `comp.py` problem, and cleaned up the mess in `cmake/UseHALComp.cmake` as well.

Do you think we should simply remove the `.gitignore` files in this tree?

I fixed the include directories as you suggested.  There are still a few places labeled `FIXME` in `UseHALComp.cmake` and `hal/cython/machinekit/CMakeLists.txt` that need to be fixed once other `CMakeLists.txt` files are in place and I understand how `UseHALComp.cmake` can be distributed in a `machinekit-dev` package (along with or replaced by a `FindHALComp.cmake` file).

Thanks for the review, and thanks for holding my hand with this.

**Comment by bobvanderlinden** [comment]
@zultron Oh I just pushed a (I think) similar change on top of yours. However, it doesn't compile for me yet (your version as well as mine). There is a problem with Cython's generated c file. For instance:

It generates:
```
__Pyx_PyInt_From_comp_type(comp_type value);
```
But the compiler tells me it should be:
```
__Pyx_PyInt_From_comp_type(enum comp_type value);
```
I have tried both clang and gcc and both give me errors on those lines. (clang was a bit more helpful by suggesting the `enum` prefix)

It probably could be solved by a `typedef` in `hal.h`, but I'm not entirely sure that's the right way to go (as it might be incompatible with existing code that relies on hal.h). It could probably also be 'resolved' by replacing `comp_type` with `enum comp_type` after running cython. Could be worth a try, but I'll need to give that a go tomorrow or later.

Also, should we continue the conversation here (does anyone here care about the details? :P) or should we continue in https://github.com/bobvanderlinden/machinekit/pull/1 ?

**Comment by RunningLight** [comment]
Yes, people here care about the details.

**Comment by zultron** [comment]
@bobvanderlinden, Ah, I didn't notice that you'd pulled my patches.  I guess I should close out bobvanderlinden#1.

The top patch in the PR gets rid of the ugly stuff in `UseHALComp.cmake`.  I can pick out those changes into a new PR if you're interested.

I think we should keep the conversation in this repo, but perhaps start a new issue specifically about CMake.  Opinions?

What version of CMake are you running?  I'm on Jessie:
```
$ dpkg-query -W cython
cython	0.21.1-1
```

**Comment by bobvanderlinden** [comment]
I rebase on your version and fixed a couple of the issues. Not sure why it would compile for you, but I needed to change this in the Cython files:
https://github.com/bobvanderlinden/machinekit/commit/75bac131ede7458b07aab95e7bc377da0960ee55
Because `hal.h` does not have typedefs for those enums:
https://github.com/bobvanderlinden/machinekit/blob/cmake/projects/hal/linuxcnchal/include/hal.h#L202

I also had trouble with `sim_axis_hardware.comp` as it seemed c-functions may not be declared inside a FUNCTION.

I was doing this on my laptop (with Nix), since I don't have a Debian VM here. I'll also give it a try when I'm on my desktop (with VM) again.

**Comment by bobvanderlinden** [comment]
@zultron I wanted to ask, at the moment I'm building `linuxcnc.a` with cmake. It has a number of `extern`s in there that any .so or executable should implement. For example: `emcTrajSetHome(EmcPose)`. The only file that seems to implement this function is `src/emc/task/taskintf.cc`, which is essentially only for `linuxcncsvr`. When I want to build any of the other binaries that are indirectly depending on `linuxcnc.a`, I get undefined references.

Do you know how this works exactly? I couldn't figure this out from the Submakefiles and I wasn't sure whether there is a better way to handle this. Would it be possible to build linuxcnc.a without dangling externs?

**Comment by bobvanderlinden** [comment]
Never mind my last comment. I had made a dumb mistake quite a while ago for `linuxcncini`, which affected many other build targets. It now conforms to the old buildsystem and makes sense again.

It is now possible to build `linuxcncsvr`, `io`, `milltask`, `halcmd` and probably some others I'm forgetting. From what I found skimming through the `linuxcnc`/`machinekit` shell script, it seems these should be the executables needed to start the core of Machinekit (without GUIs, just HAL and motor). I haven't been able to start things correctly, due to there being no correct install rules and paths are still incorrect, but it should be close now I think. (crosses fingers)

**Comment by bobvanderlinden** [comment]
I forgot about the `rtapi_app_*` and `rtapi_msgd`. I wasn't sure what to do with all the 'flavors' of rtapi, so I just did `rtapi_app_posix`. The install rules for the libraries and executables are also added as well as the `configs` directory.

However, it doesn't seem to work yet. I tried executing the following lines in this order in separate terminals:
```
linuxcncsvr -ini $CONFIGS/sim/axis/axis.ini
MACHINEKIT_INI=/etc/machinekit/machinekit.ini rtapi_app_posix --instance=0 --foreground --ini=/etc/machinekit/machinekit.ini --debug --svcuuid=6d7d46ea-d2f9-459f-a9b3-17887024ea19
halcmd ping
```
Watching syslog (journalctl) resulted in the following error:
```
Nov 13 20:33:53 bob-laptop rtapi:0[30775]: rtapi_app:0: ERROR: global segment magic not changing to ready: magic=0x0
Nov 13 20:33:53 bob-laptop rtapi:0[30775]: rtapi:0: FATAL - failed to attach to global segment
```
I think I'm overlooking something obvious, but it's hard to tell what.
The commands above are somewhat extracted from `linuxcnc.in`, so there's a good chance it's still missing something. I'm wondering what the minimal set of commands/daemons is to set up HAL.

**Comment by zultron** [comment]
Hi @bobvanderlinden,

As for `hal.h`, I don't know why the Jessie Cython handles the `enum` statements and yours don't, or what the proper fix is, adding `typedef` in `hal.h` or doing what you did.  I'm placing my bets with you, though.  ;)

I haven't tried your branch yet.  To run a minimal HAL, try `realtime start`, and `halrun` with some `.hal` file, maybe from the `tests` directory.  Get debugging to `stderr` with `export DEBUG=5; export MSGD_OPTS=-s`.

Great progress!  I'll help out with flavors next week, only targeting POSIX, RT_PREEMPT and Xenomai.

**Comment by bobvanderlinden** [comment]
`realtime` and the configuration files are implemented now. However `setuid` still needs to be integrated somehow. Or is there a way to test things without `setuid`?

**Comment by ArcEye** [comment]
This discussion died.

The build system may not be the optimum in some opinions, but it does work and no-one has come forward to do the work to replace with a CMake system.

I managed to adapt it to build the Machinekit-HAL repo without too much trouble, in some ways it is best to stick with what you are familiar with.
