### ISSUE TITLE
Coding style and static analysis

### ISSUE THREAD

**Issue by machinekoder** [machinekit/machinekit#391]
We should enforce a specific coding style for every language in the project. This can e.g. be done by using astyle. My code editor (Kate) always shows mixed indentations  (tabs and spaces) everywhere. This makes the code unreadable on some platforms and is possible error source.

Furthermore every piece of code that is commit should be checked with suitable static code analysis tool. For C and C++ cppcheck and clang might be suitable. For Python pep8 is the way to go. This ensures that common error will not make its way into the project.

**Comment by strahlex** [comment]
Is there any tool that cleans up tabs and spaces? I think it makes sense to check for such problems before merging a patch. Most editors do not display tabs and spaces differently and thats really annoying.

I would not force a specific coding style on anyone, but providing a standard astyle file for C,C++ and Python would make sense. Especially for those who do not program frequently and need some guidelines anyway.

Static analysis is whole different thing and should be enforced if possible. Well, it can be annoying and too strict (MISRA C), but it could prevent many ugly bugs introduced in projects.

**Comment by mhaberler** [comment]
yes: Emacs indent-region.

Please use the settings for C++ (put in your .emacs):

(setq c-default-style
      '((other . "gnu")))
(setq c-basic-offset 4)

**Comment by strahlex** [comment]
I just create a PR to the Qt project and came across a high sophisticated sanity checking system. Something like this could be useful for us too: https://wiki.qt.io/Early_Warning_System

**Comment by strahlex** [comment]
E.g. the use to sanitize commit messages and do some basic checks like indentation: https://github.com/qtproject/qtrepotools/tree/master/git-hooks

**Comment by bobvanderlinden** [comment]
Having a check for code-style in CI could have some benefits. Could we use the qtrepotools somehow to reject PRs that do not adhere to the style guide? Otherwise: do you know which tools we'd need for this?

Also, to adhere to the style guide, the current code needs to be cleaned up. What is the best approach for this? One large commit at some point?

**Comment by luminize** [comment]
> Also, to adhere to the style guide, the current code needs to be cleaned up. What is the best approach for this? One large commit at some point?

Can we generate a list where stuff is bad?
Then we make small packets, because this is cleaning up, not developing, people can chime in, and work in parallel. Like a work-packet which can be done in 30 mins so somebody can finish a part, make a PR and get to sleep with a satisfied feeling.

parallellism and small bites are the key IMO.

**Comment by bobvanderlinden** [comment]
@luminize I think a lot can be done automatically, like tabs/spaces, but I'm not sure whether that's a good idea for the current code-base.

**Comment by zultron** [comment]
@bobvanderlinden I'd love to integrate a coding style check into CI.

The main concern I'm aware of for mass cleanups is making it hard to perform merges.  If we did do something like this, it should definitely be limited to the Machinekit core code (RTAPI + HAL), which just a small number of people contribute to.

Mass cleanups should be kept out of the CNC application code, since we're preparing to spin it out and leave maintenance for other projects.  Any changes to that code to work with MK core should be easy to pick off into other LCNC forks.

**Comment by strahlex** [comment]
There is GitHub extension for doing automatic code analysis for pull requests: https://github.com/integrations/code-climate

**Comment by bobvanderlinden** [comment]
@strahlex Code Climate doesn't seem to support C/C++ (yet?). It does do Python though, so maybe Travis and Code Climate could be combined? It could also be very usable for related Python and JS projects too.

**Comment by strahlex** [comment]
Might be useful too: http://editorconfig.org/

**Comment by strahlex** [comment]
Just have seen `flake8` can be used to check Python PEP8 rules for CI.

**Comment by strahlex** [comment]
Frama-C acts both as static code analysis tool and as theorem prover if required. Could be useful for checking C HAL components e.g.

**Comment by machinekoder** [comment]
I just added Machinekit to Coverity Scan: https://scan.coverity.com/projects/machinekit-machinekit

Let's see if it proves useful.

**Comment by luminize** [comment]
> On 13 Mar 2017, at 09:48, Alexander Rössler <notifications@github.com> wrote:
> 
> I just added Machinekit to Coverity Scan: https://scan.coverity.com/projects/machinekit-machinekit
> 
> Let's see if it proves usefull
> 
Interesting.
I wonder if a lot of checking for sizes in buffer copy for example is left out on purpose of just bad programming.
http://cwe.mitre.org/top25/#CWE-120

**Comment by machinekoder** [comment]
@luminize In a lot of cases we are not dealing with user input, so not checking the data size might be safe. However, I cannot think of any good reason why we shouldn't write the copy functions in a safe way as it is basically for free to do so.

**Comment by machinekoder** [comment]
Using editorconfig is pretty easy to achieve: https://github.com/qtquickvcp/QtQuickVcp/blob/master/.editorconfig

**Comment by luminize** [comment]
> On 07 Apr 2017, at 18:37, Alexander Rössler wrote:
> Using editorconfig is pretty easy to achieve: https://github.com/qtquickvcp/QtQuickVcp/blob/master/.editorconfig
> 

Yeah, i'm using it in one of my own projects. Let's put one in the main MK repo for the languages in use, and people who use editorconfig will be served.

Let's make it optional to use it, and not mandatory.

Then we can close the coding style part.
