### ISSUE TITLE
why does an install from Debian packages create /root/machinekit directory?

### ISSUE THREAD

**Issue by RunningLight** [machinekit/machinekit#541]
I rarely install Machinekit from Debian packages so maybe I just never noticed this before. Near the end of the install process, after the hotplug events dispatcher and rsyslogd stop and start, I get this console message:

```
Creating machinekit directory
chown: cannot access `/root/machinekit.': No such file or directory
```

As it happens, just such a directory does get created in the install process but why `/root/machinekit`?

[My apologies if this has come up earlier; my ability to search GitHub issues seems inadequate to the task.]

**Comment by ArcEye** [comment]
It is because the postinst script uses the $HOME env var to create the directory, 
but because it is being installed using sudo, it is picking up the user as root.

Has been changed to $SUDO_USER for now, will be amended again soon to check for and create the dir when MK is launched, to cater for different users and ensure the dir is in the right place.
