### ISSUE TITLE
Info on Creating Vagrant VMs for Machinekit missing

### ISSUE THREAD

**Issue by machinekoder** [machinekit/machinekit#765]
Today I stumbled upon  [Vagrant](https://www.vagrantup.com/). This tool claims to simplify setting development environment using VirtualBox and other VMs. The functionality is very simple but powerful:

**To create a Vagrant configuration:**
1. Choose a base image (e.g. Debian Jessie)
2. Create a provisioning script that install software (in our case Machinekit, Qt, etc...)

**To use it:**
1. Install VirtualBox and Vagrant
2. Clone a git repo containing the Vagrant config
3. Start vagrant
4. Use the VM
5. Reset the when you broke it

The advantage over the naked VirtualBox VM is that one can fully automate the setup process and a working development environment can be set up in a few keystrokes.

I can imagine creating 3 different configurations:
- a Machinekit test VM -> package install to try out Machinekit on the desktop
- a Machinekit developer VM with RIP install and development tools
- a Machinekit SDK config with all the Qt UI tools

**Comment by strahlex** [comment]
The best thing about Vagrant is that all configs could share the same base provisioning script setting up the base Debian environment. Mixing the provisioning scripts together should also be possible.

**Comment by luminize** [comment]
That sounds very usefull!

**Comment by luminize** [comment]
I've installed vagrant and I already had virtual box.
`$ vagrant box add debian/jessie64` installs a debian jessie box.
will try this out further, because this could be the "easy install" regarding a VM

**Comment by strahlex** [comment]
Yes, I already crated a basic Machinekit package provisioner. Will upload the repo when I come home.

**Comment by strahlex** [comment]
Here we go: https://github.com/strahlex/machinekit-vagrant
vagrant up sets up a a Jessie VM with Machinekit packages

**Comment by luminize** [comment]
I'm just off to my project but will check this evening for sure. Did a bare Jessie setup yesterday evening.

**Comment by luminize** [comment]
this could solve https://github.com/machinekit/machinekit/issues/229

**Comment by luminize** [comment]
@strahlex I try your vagrant file, and the line https://github.com/strahlex/machinekit-vagrant/blob/master/Vagrantfile#L40 is problematic since different users have different locations.
I'll make a PR for that.

so, here are my results.
after `vagrant up` letting the entire terminal run to the the prompt returns.
```
==> default: Setting up machinekit (0.1.1479-1da.bbot.pr764.gitce22b09~1jessie) ...
==> default: Restarting udev (via systemctl): udev.service
==> default: .
==> default: Setting up machinekit-posix (0.1.1479-1da.bbot.pr764.gitce22b09~1jessie) ...
==> default: Processing triggers for libc-bin (2.19-18+deb8u1) ...
==> default: Processing triggers for python-support (1.0.15) ...
Bass-MacBook-Pro-3:machinekit-vagrant basdebruijn$
```

The VM gives me the "oh no" feeling
<img width="720" alt="screen shot 2015-10-08 at 19 51 05" src="https://cloud.githubusercontent.com/assets/2206842/10374969/48f256a0-6df6-11e5-8b31-1b31d9c3f287.png">

I sent the shutdown signal to the VM.
then `vagrant up` again in the terminal and voila, the LXDE starts.

@mhaberler @strahlex We might make a machinekit organisation repo with different folders for different setups, like packages for trying out, a git based development image, Alex' QT work.

I'm very excited about this :)

**Comment by strahlex** [comment]
@luminize I have to find a way to start LXDE right away.

**Comment by luminize** [comment]
I just do `vagrant up` and that starts the VM and that just starts LXDE. I experience no troubles.

**Comment by luminize** [comment]
@machinekoder This should be in the documentation, right? If still needed please open a new issue in machinekit-docs.
