### ISSUE TITLE
Maximum number of tools

### ISSUE THREAD

**Issue by machinekoder** [machinekit/machinekit#989]
The maximum number of tools is currently hard coded and limited to 56 (see https://github.com/machinekit/machinekit/blob/master/src/emc/nml_intf/emctool.h#L23). Would it make any problems to raise the number of supported tools to 100?

**Comment by ArcEye** [comment]
See this from someone you know in US :smile: 
http://permalink.gmane.org/gmane.linux.distributions.emc.devel/14329

It would be worth chasing down the whole thread, Andy Pugh looked at the whole tool table issue some while back with a view to changing it to SQL or similar.

Looks like the only real issue is ensuring the buffers are large enough to accommodate the increased structure size.
